package com.youth.habittracker.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6366f1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFe0e7ff)
val md_theme_light_onPrimaryContainer = Color(0xFF1e3a8a)
val md_theme_light_secondary = Color(0xFF64748b)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFe2e8f0)
val md_theme_light_onSecondaryContainer = Color(0xFF1e293b)
val md_theme_light_tertiary = Color(0xFF8b5cf6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFede9fe)
val md_theme_light_onTertiaryContainer = Color(0xFF4c1d95)
val md_theme_light_error = Color(0xFFdc2626)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFfee2e2)
val md_theme_light_onErrorContainer = Color(0xFF7f1d1d)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1f2937)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1f2937)
val md_theme_light_surfaceVariant = Color(0xFFf8fafc)
val md_theme_light_onSurfaceVariant = Color(0xFF64748b)
val md_theme_light_outline = Color(0xFFe2e8f0)
val md_theme_light_outlineVariant = Color(0xFFcbd5e1)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF1e293b)
val md_theme_light_inverseOnSurface = Color(0xFFf1f5f9)
val md_theme_light_inversePrimary = Color(0xFFa5b4fc)
val md_theme_light_surfaceDim = Color(0xFFf1f5f9)
val md_theme_light_surfaceBright = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFf8fafc)
val md_theme_light_surfaceContainer = Color(0xFFf1f5f9)
val md_theme_light_surfaceContainerHigh = Color(0xFFe2e8f0)
val md_theme_light_surfaceContainerHighest = Color(0xFFcbd5e1)

val md_theme_dark_primary = Color(0xFF818cf8)
val md_theme_dark_onPrimary = Color(0xFF1e3a8a)
val md_theme_dark_primaryContainer = Color(0xFF1e40af)
val md_theme_dark_onPrimaryContainer = Color(0xFFdbeafe)
val md_theme_dark_secondary = Color(0xFF94a3b8)
val md_theme_dark_onSecondary = Color(0xFF0f172a)
val md_theme_dark_secondaryContainer = Color(0xFF1e293b)
val md_theme_dark_onSecondaryContainer = Color(0xFFe2e8f0)
val md_theme_dark_tertiary = Color(0xFFa78bfa)
val md_theme_dark_onTertiary = Color(0xFF4c1d95)
val md_theme_dark_tertiaryContainer = Color(0xFF6d28d9)
val md_theme_dark_onTertiaryContainer = Color(0xFFede9fe)
val md_theme_dark_error = Color(0xFFf87171)
val md_theme_dark_onError = Color(0xFF7f1d1d)
val md_theme_dark_errorContainer = Color(0xFF7f1d1d)
val md_theme_dark_onErrorContainer = Color(0xFFfecaca)
val md_theme_dark_background = Color(0xFF0f172a)
val md_theme_dark_onBackground = Color(0xFFf1f5f9)
val md_theme_dark_surface = Color(0xFF1e293b)
val md_theme_dark_onSurface = Color(0xFFe2e8f0)
val md_theme_dark_surfaceVariant = Color(0xFF1e293b)
val md_theme_dark_onSurfaceVariant = Color(0xFF94a3b8)
val md_theme_dark_outline = Color(0xFF475569)
val md_theme_dark_outlineVariant = Color(0xFF1e293b)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFe2e8f0)
val md_theme_dark_inverseOnSurface = Color(0xFF1e293b)
val md_theme_dark_inversePrimary = Color(0xFF1e40af)
val md_theme_dark_surfaceDim = Color(0xFF1e293b)
val md_theme_dark_surfaceBright = Color(0xFF334155)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0f172a)
val md_theme_dark_surfaceContainerLow = Color(0xFF1e293b)
val md_theme_dark_surfaceContainer = Color(0xFF334155)
val md_theme_dark_surfaceContainerHigh = Color(0xFF475569)
val md_theme_dark_surfaceContainerHighest = Color(0xFF64748b)

// Custom colors for the app
val YouthBlue = Color(0xFF6366f1)
val YouthLightBlue = Color(0xFF818cf8)
val YouthBackground = Color(0xFFf8f9fa)
val YouthWhite = Color(0xFFFFFFFF)

val SuccessGreen = Color(0xFF10b981)
val WarningOrange = Color(0xFFf59e0b)
val ErrorRed = Color(0xFFef4444)
val NeutralGray = Color(0xFF6b7280)

// Category colors
val CategoryHealth = Color(0xFF10b981)
val CategoryWork = Color(0xFF3b82f6)
val CategoryPersonal = Color(0xFF8b5cf6)
val CategoryFitness = Color(0xFFf59e0b)
val CategoryLearning = Color(0xFFec4899)
val CategoryCreativity = Color(0xFFf97316)
val CategorySocial = Color(0xFF06b6d4)
val CategoryFinance = Color(0xFF84cc16)